require(palmerpenguins)
dat_ade = droplevels(subset(penguins, species == "Adelie"))
hist(dat_ade$body_mass_g, main = "Adelie Penguins: Body Mass", xlab = "body mass (g)")
boxplot(dat_ade$body_mass_g ~ dat_ade$sex, main = "Body Mass of Adelie Penguins", xlab = "sex", ylab = "body mass (g)")
sex_f = droplevels(subset(dat_ade, sex == "female"))
sex_m = droplevels(subset(dat_ade, sex == "male"))
t.test(sex_f$body_mass_g, mu = 0)
t.test(sex_m$body_mass_g, alternative = "greater", mu = 4000)
t.test(sex_m$body_mass_g, alternative = "less", sex_f$body_mass_g)
