#install.packages("here")
require(here)
here()
dat_catrate = read.csv(here("data", "catrate.csv"))
head(dat_catrate)
dat_rope = read.csv(here("data", "rope.csv"))
dat_delomys = read.csv(here("data", "delomys.csv"))
head(dat_delomys)
head(dat_rope)
plot(dat_delomys$body_mass, dat_delomys$body_length, main = "Ollie's Plot of Delomys Body Mass vs. Body Length", xlab = "Body Mass", ylab = "Body Length")
